Repository COOTAM/COTAM_FE, pull requests merged in 2024-10, with the labels that each got.

#23 Feat: 코탐 소개 페이지, Tab
  src/app/about/TabAbout.tsx
  src/app/about/constants.ts
  src/app/about/page.tsx
  src/components/common/Tab.tsx
  src/components/common/TimeTable.tsx
Labels: FEAT

#25 Feat: 모집안내 페이지
  src/app/_components/Header.tsx
  src/app/layout.tsx
  src/app/recruit/constant.ts
  src/app/recruit/page.tsx
  src/components/common/DescriptionCard.tsx
  src/components/common/FAQAccordion.tsx
  src/components/common/MenuButton.tsx
  src/components/common/MenuDrawer.tsx
Labels: FIX, FEAT, REFACTOR

#28 Refactor: 페이지 별 태그 정리
  src/app/about/TabAbout.tsx
  src/app/people/constants.ts
  src/app/people/page.tsx
  src/components/common/DescriptionCard.tsx
  src/components/common/Tab.tsx
Labels: REFACTOR

#29 feat: 메인페이지 작업
  package.json
  public/assets/icons/Bang.svg
  public/assets/icons/Border-Top.svg
  public/assets/image/Graphic-Display.png
  public/assets/image/Pixel16-Book.png
  public/assets/image/Pixel16-Human.png
  public/assets/image/main_icon.png
  src/app/_components/Header.tsx
  src/app/_components/WithCotamButton.tsx
  src/app/_components/home/AboutCotam.tsx
  src/app/_components/home/Closing.tsx
  src/app/_components/home/Cotam.tsx
  src/app/_components/home/CotamPeople.tsx
  src/app/_components/home/FAQ.tsx
  src/app/_components/home/GraphicDisplay.tsx
  src/app/_components/home/ImageBox.tsx
  src/app/_components/home/Introduce.tsx
  src/app/_components/home/LinkButton.tsx
  src/app/_components/home/TopMoveBox.tsx
  src/app/page.tsx
  src/components/common/BorderTop.tsx
  src/constants/ui.ts
  src/hooks/useIntersect.ts
  src/hooks/useIsVisible.ts
  yarn.lock
Labels: FEAT

#31 Refactor: QA목록 변경, FAQ 내용 추가
  src/app/_components/WithCotamButton.tsx
  src/app/_components/home/AboutCotam.tsx
  src/app/about/TabAbout.tsx
  src/app/people/_components/PeopleCount.tsx
  src/app/people/page.tsx
  src/app/recruit/constant.ts
  src/app/recruit/constant.tsx
  src/app/recruit/page.tsx
  src/components/common/FAQAccordion.tsx
Labels: REFACTOR

#32 Feat: 사람들 데이터 추가, 자격 요건 수정
  src/app/people/constants.ts
  src/app/people/page.tsx
  src/app/recruit/page.tsx
Labels: FEAT

#33 Feat: QA 내용 정리
  public/assets/icons/BorderTop.svg
  public/assets/image/Pixel16-Desktop.png
  src/app/_components/WithCotamButton.tsx
  src/app/_components/home/AboutCotam.tsx
  src/app/_components/home/Closing.tsx
  src/app/_components/home/Cotam.tsx
  src/app/_components/home/CotamPeople.tsx
  src/app/_components/home/FAQ.tsx
  src/app/_components/home/Introduce.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/BorderTop.tsx
Labels: FEAT

#34 fix: 레이아웃 오류 수정
  src/app/layout.tsx
Labels: FIX

#35 Chore: 사람들 이미지 추가
  public/assets/image/people/allen.webp
  public/assets/image/people/dara.webp
  public/assets/image/people/herim.webp
  public/assets/image/people/quakka.webp
  public/assets/image/people/reco.webp
  src/app/people/constants.ts
  src/app/people/page.tsx
Labels: CHORE

#36 Feat: 홈페이지에 FAQ 추가
  public/assets/icons/MainIconRed.svg
  public/assets/image/Pixel16-Book.png
  public/assets/image/Pixel16-Desktop.png
  public/assets/image/Pixel16-Human.png
  public/assets/image/main_icon.png
  src/app/_components/home/AboutCotam.tsx
  src/app/_components/home/CotamPeople.tsx
  src/app/_components/home/FAQ.tsx
  src/app/_components/home/ImageBox.tsx
  src/app/_components/home/Introduce.tsx
  src/app/about/TabAbout.tsx
  src/app/people/_components/PeopleCount.tsx
  src/app/recruit/page.tsx
  src/components/FAQList.tsx
  src/components/common/FAQAccordion.tsx
  src/constants/externalLinks.ts
  src/constants/faqData.tsx
  src/constants/studyStats.ts
  src/hooks/useIntersect.ts
  src/hooks/useIsCSR.ts
Labels: FEAT

#39 Feat: op-image 추가, robots.ts 추가
  src/app/_components/Header.tsx
  src/app/layout.tsx
  src/app/opengraph-image.png
  src/app/robots.ts
Labels: FEAT

#40 Feat: 네트워킹 이미지 추가 / 제인,레이첼 소개 추가
  public/assets/image/networking.webp
  public/assets/image/people/jane.webp
  public/assets/image/study.webp
  src/app/_components/home/AboutCotam.tsx
  src/app/_components/home/ImageBox.tsx
  src/app/people/constants.ts
Labels: FEAT

#42 [QA] 다 -> 요
  src/app/_components/home/AboutCotam.tsx
  src/app/about/constants.ts
  src/app/people/constants.ts
  src/constants/faqData.tsx
Labels: CHORE

#43 fix: 스타일 꺠짐 수정
  src/app/_components/home/CotamPeople.tsx
Labels: FIX

#44 fix: 모집기간 수정
  src/app/recruit/page.tsx
Labels: FEAT

#45 Fix: 모집안내 제목 색상 변경
  src/app/recruit/page.tsx
Labels: FIX

#46 Fix: 자주 묻는 질문 제목 색상 변경
  src/app/recruit/page.tsx
Labels: FIX

#48 Feat: 모집중/모집중 아님 설정값 추가
  src/app/_components/home/Closing.tsx
  src/app/_components/home/Introduce.tsx
  src/app/_components/home/WithCotamButton.tsx
  src/app/recruit/_components/ApplicationRequirements.tsx
  src/app/recruit/_components/ContactSection.tsx
  src/app/recruit/_components/FAQSection.tsx
  src/app/recruit/_components/RecruitmentPeriod.tsx
  src/app/recruit/page.tsx
  src/constants/recruitConfig.ts
  src/constants/studyStats.ts
Labels: FEAT, REFACTOR
