Repository COOTAM/COTAM_FE, pull requests merged in 2024-09, with the labels that each got.

#14 SVGR 세팅 + 아이콘 추가
  next.config.mjs
  package.json
  public/assets/icons/ArrowUpBlue.svg
  public/assets/icons/ArrowUpRed.svg
  public/assets/icons/BookRed.svg
  public/assets/icons/CoffeeBlue.svg
  public/assets/icons/CoffeeRed.svg
  public/assets/icons/DesktopBlue.svg
  public/assets/icons/DesktopRed.svg
  public/assets/icons/GameBlack.svg
  public/assets/icons/Hamburger.svg
  public/assets/icons/HandBlue.svg
  public/assets/icons/HandMetalRed.svg
  public/assets/icons/HandRed.svg
  public/assets/icons/HumanRed.svg
  public/assets/icons/ScrollRed.svg
  public/assets/icons/TargetRed.svg
  public/assets/icons/WarningBlue.svg
  src/app/page.tsx
  yarn.lock
Labels: STYLE

#15 Vercel 자동 배포 추가
  .github/workflows/deploy.yml
  build.sh
Labels: CI

#16 FEAT: Button, DescriptionCard 컴포넌트 추가
  package.json
  src/app/page.tsx
  src/components/common/Button.tsx
  src/components/common/DescriptionCard.tsx
  src/lib/utils.ts
  yarn.lock
Labels: FEAT

#18 Feat: Header,Footer 추가, 페이지 별 타이틀 설정
  public/assets/background/PixelGradient.png
  public/assets/logo/Cotam.svg
  src/app/_components/Footer.tsx
  src/app/_components/Header.tsx
  src/app/about/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/people/page.tsx
  src/app/recruit/page.tsx
  src/constants/routes.ts
  tailwind.config.ts
Labels: FEAT

#19 Feat: 아코디언 컴포넌트
  src/components/common/Accordion.tsx
  typography.ts
Labels: FEAT
