Repository COOTAM/COTAM_FE, pull requests merged in 2025-01, with the labels that each got.

#49 Chore: 구성원 및 스터디 횟수 상수 변경
  public/assets/image/people/dara.webp
  public/assets/image/people/quakka.webp
  src/app/_components/home/AboutCotam.tsx
  src/app/people/constants.ts
  src/constants/studyStats.ts
Labels: CHORE

#51 Refactor: 탭 공통 구조 변경
  .prettierrc
  package.json
  public/next.svg
  public/vercel.svg
  src/app/_components/Footer.tsx
  src/app/_components/Header.tsx
  src/app/_components/home/AboutCotam.tsx
  src/app/_components/home/Cotam.tsx
  src/app/_components/home/CotamPeople.tsx
  src/app/_components/home/FAQ.tsx
  src/app/_components/home/GraphicDisplay.tsx
  src/app/_components/home/ImageBox.tsx
  src/app/_components/home/Introduce.tsx
  src/app/_components/home/TopMoveBox.tsx
  src/app/_components/home/WithCotamButton.tsx
  src/app/about/TabAbout.tsx
  src/app/about/_components/NetworkingTabItem.tsx
  src/app/about/_components/StudyTabItem.tsx
  src/app/about/constants.ts
  src/app/about/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/people/_components/PeopleCount.tsx
  src/app/people/page.tsx
  src/app/recruit/_components/ContactSection.tsx
  src/app/recruit/_components/RecruitmentPeriod.tsx
  src/app/recruit/page.tsx
  src/app/robots.ts
  src/app/sitemap.ts
  src/components/FAQList.tsx
  src/components/common/Button.tsx
  src/components/common/DescriptionCard.tsx
  src/components/common/FAQAccordion.tsx
  src/components/common/MenuDrawer.tsx
  src/components/common/Tab.tsx
  src/components/common/Tabs.tsx
  src/hooks/useIsCSR.ts
  src/hooks/useIsVisible.ts
  src/lib/utils.ts
  yarn.lock
Labels: REFACTOR

#52 feat: 사람들 job 수정
  src/app/people/constants.ts
Labels: FEAT

#53 Refactor: MenuDrawer->Drawer로 이름 변경하며 전체적인 구조 변경
  src/app/_components/home/AboutCotam.tsx
  src/app/_components/home/FAQ.tsx
  src/app/_components/home/WithCotamButton.tsx
  src/app/_components/layout/Footer.tsx
  src/app/_components/layout/HamburgerMenu.tsx
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/MenuItem.tsx
  src/app/about/_components/StudyTabItem.tsx
  src/app/about/constants.ts
  src/app/about/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/people/_components/MemberCard.tsx
  src/app/people/_components/MemberCount.tsx
  src/app/people/constants.ts
  src/app/people/page.tsx
  src/app/people/types.ts
  src/app/recruit/_components/ApplicationRequirements.tsx
  src/app/recruit/_components/ContactSection.tsx
  src/app/recruit/_components/RecruitmentPeriod.tsx
  src/components/BorderTop.tsx
  src/components/Button.tsx
  src/components/DescriptionCard.tsx
  src/components/Drawer.tsx
  src/components/FAQAccordion.tsx
  src/components/FAQList.tsx
  src/components/Tabs.tsx
  src/components/TimeTable.tsx
  src/components/common/MenuButton.tsx
  src/components/common/MenuDrawer.tsx
  tailwind.config.ts
Labels: REFACTOR
